StartupEvents.registry('block', event => {
  event.create('charcoal_block')
    .displayName('Block of Charcoal')
    .soundType('stone')
    .hardness(5)
    .resistance(6)
    .tagBlock('minecraft:mineable/pickaxe')

  event.create('budding_durite')
    .displayName('Budding Durite')
    .soundType('amethyst')
    .tagBlock('minecraft:mineable/pickaxe')
    
  event.create('cracked_diamond_block')
    .displayName('Cracked Diamond Block')
    .soundType('stone')
    .tagBlock('minecraft:mineable/pickaxe')
    .hardness(5)
    .resistance(6)
})