//potato
StartupEvents.registry('item', event => {
    event.create('blazing_upgrade_template').displayName('Blazing Upgrade Template')
    event.create('gilded_upgrade_template').displayName('Guilded Upgrade Template')
    event.create('rose_quartz_dust').displayName('Rose Quartz Dust')
    event.create('carbon_dust').displayName('Carbon Dust')
    event.create('brass_pipe').displayName('Brass Pipe')
    event.create('industrial_iron_pipe').displayName('Industrial Iron Pipe')
    event.create('obsidian_bucket').displayName('Obsidian Bucket').maxStackSize(16)
    event.create('obsidian_lava_bucket').displayName('Obsidian Lava Bucket').maxStackSize(1)
    event.create('obsidian_water_bucket').displayName('Obsidian Water Bucket').maxStackSize(1)
    event.create('obsidian_powder_snow_bucket').displayName('Obsidian Powder Snow Bucket').maxStackSize(1)
    
    event.create('obsidian_milk_bucket').displayName('Obsidian Milk Bucket').useAnimation('drink')
        .food(food => {
            food.hunger(0)
                .saturation(0)
                .alwaysEdible()
                .eaten(context => {
                    context.item.shrink(1)
                    context.player.give('kubejs:obsidian_bucket')
                    context.player.potionEffects.clear()
                })
        }).maxStackSize(1)

    event.create('rose_gold_sheet').displayName('Rose Gold Sheet')
    event.create('mimic_spawn_egg').displayName('Mimic')
    event.create('diamond_nuggie').displayName('Diamond Nugget')
    event.create('magic_mirror').displayName('Magic Mirror').maxStackSize(1).rarity('epic')
    event.create('cracked_magic_mirror').displayName('Magic Mirror').maxStackSize(1).rarity('rare')
    event.create('damaged_magic_mirror').displayName('Magic Mirror').maxStackSize(1).rarity('rare')
    event.create('broken_magic_mirror').displayName('Broken Magic Mirror').maxStackSize(1)
    event.create('gamblers_eye').displayName('Gamblers Eye')
    event.create('rubber_sheet').displayName('Rubber Sheet')
    event.create('dagger', 'sword').displayName('Dagger').tier('iron').attackDamageBaseline(1.0).speedBaseline(-1.0).maxStackSize(1).maxDamage(412)
})
